name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Deploy files to server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_URL }}
          username: ${{ secrets.FTP_LOGIN }}
          password: ${{ secrets.FTP_PASS }}
          server-dir: ${{ secrets.FTP_DIR }}
          protocol: 'ftp'
